// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BundleListerExpansion allows custom methods to be added to
// BundleLister.
type BundleListerExpansion interface{}

// BundleNamespaceListerExpansion allows custom methods to be added to
// BundleNamespaceLister.
type BundleNamespaceListerExpansion interface{}
