// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/ecordell/rukpak/pkg/apis/rukpak/clientset/versioned"
	internalinterfaces "github.com/ecordell/rukpak/pkg/apis/rukpak/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ecordell/rukpak/pkg/apis/rukpak/listers/rukpak/v1alpha1"
	rukpakv1alpha1 "github.com/ecordell/rukpak/pkg/apis/rukpak/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BundleInformer provides access to a shared informer and lister for
// Bundles.
type BundleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BundleLister
}

type bundleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBundleInformer constructs a new informer for Bundle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBundleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBundleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBundleInformer constructs a new informer for Bundle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBundleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RukpakV1alpha1().Bundles(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RukpakV1alpha1().Bundles(namespace).Watch(context.TODO(), options)
			},
		},
		&rukpakv1alpha1.Bundle{},
		resyncPeriod,
		indexers,
	)
}

func (f *bundleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBundleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bundleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rukpakv1alpha1.Bundle{}, f.defaultInformer)
}

func (f *bundleInformer) Lister() v1alpha1.BundleLister {
	return v1alpha1.NewBundleLister(f.Informer().GetIndexer())
}
