// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/ecordell/rukpak/pkg/apis/rukpak/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Bundles returns a BundleInformer.
	Bundles() BundleInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Bundles returns a BundleInformer.
func (v *version) Bundles() BundleInformer {
	return &bundleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
